version: "3.8"

services:
  portfolio:
    build: # Use the Dockerfile from the current directory to build container.
      context: ./portfolio/
    container_name: portfolio
    restart: on-failure
    ports:
      - "80:4000"
    depends_on:
      - "db"
    environment:
      PORTFOLIO_CONN_STRING: ${PORTFOLIO_CONN_STRING}
      TODOTECH_CONN_STRING: ${TODOTECH_CONN_STRING}
      HANGMAN_CONN_STRING: ${HANGMAN_CONN_STRING}

  karmagobot:
    build:
      context: ./karma-gobot/
    container_name: telegram-bot
    restart: on-failure
    depends_on:
      - "db"
    environment:
      TELEGRAM_BOT_API: ${TELEGRAM_BOT_API}
      KARMA_CONN_STRING: ${KARMA_CONN_STRING}

  db:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    restart: always
    environment: # add default values, see docs for more info.
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "db"

volumes: # add volume to persist data.
  my-db:
