version: "3.8"

services:
  portfolio:
    build: # Use the Dockerfile from the current directory to build container.
      context: .
    container_name: portfolio
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - "db"
    networks:
      - web

  db:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: # add default values, see docs for more info.
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "5432:3306"
    networks:
      - web

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    networks:
      - web

volumes: # add volume to persist data.
  my-db:

networks:
  web:
    driver: overlay
