version: "3"

services:
  hangman:
    container_name: "hangman-api"
    build: .
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - api:/usr/src/go
    depends_on:
      - api-postgres
    networks:
      - api-bridge

  api-postgres:
    image: postgres:latest
    container_name: hangman-pg
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - api-bridge

  pgadmin:
    image: dpage/pgadmin4
    container_name: api-postgres-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - api-postgres
    ports:
      - 5050:5050
    networks:
      - api-bridge
    restart: unless-stopped

volumes:
  api:
  database_postgres:

networks:
  api-bridge:
    driver: bridge
